
Vagrant.configure("2") do |config|

  config.vm.box = "debian/buster64"

  # The Nginx VM
  config.vm.define "nodejsapp_nginx" do |nodejsapp_nginx|
    nodejsapp_nginx.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end

    nodejsapp_nginx.vm.network "private_network", ip: "192.168.33.20"
    nodejsapp_nginx.vm.hostname = "nodejsapp-nginx"

    nodejsapp_nginx.vm.provision "shell", inline: <<-SHELL
      echo "Adding SSH key"
      echo 'ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAHyKTX5ZyVK84+BdnSlfygPD6P+P8ehHPeelXxVKyeaomlKWMFB2/z1eyOtNTpFgBD7NQLbHQ+VXxbSa/35i4tRXQAblGpCr+GrrkSohYNV+jqAuc0z8gkKGs6a6PR8gZCvDakDH6jSM9PxkOkuN6S9q09Wz7sqS7HPpgzMSEzGeFiv/Q==' >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  # The Nodejs 1st backend VM
  config.vm.define "nodejsapp_backend1" do |nodejsapp_backend1|
    nodejsapp_backend1.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end

    nodejsapp_backend1.vm.network "private_network", ip: "192.168.33.21"
    nodejsapp_backend1.vm.hostname = "nodejsapp-backend1"

    nodejsapp_backend1.vm.provision "shell", inline: <<-SHELL
      echo "Adding SSH key"
      echo 'ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAHyKTX5ZyVK84+BdnSlfygPD6P+P8ehHPeelXxVKyeaomlKWMFB2/z1eyOtNTpFgBD7NQLbHQ+VXxbSa/35i4tRXQAblGpCr+GrrkSohYNV+jqAuc0z8gkKGs6a6PR8gZCvDakDH6jSM9PxkOkuN6S9q09Wz7sqS7HPpgzMSEzGeFiv/Q==' >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  # The Nodejs 2nd backend VM
  config.vm.define "nodejsapp_backend2" do |nodejsapp_backend2|
    nodejsapp_backend2.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end

    nodejsapp_backend2.vm.network "private_network", ip: "192.168.33.22"
    nodejsapp_backend2.vm.hostname = "nodejsapp-backend2"

    nodejsapp_backend2.vm.provision "shell", inline: <<-SHELL
      echo "Adding SSH key"
      echo 'ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAHyKTX5ZyVK84+BdnSlfygPD6P+P8ehHPeelXxVKyeaomlKWMFB2/z1eyOtNTpFgBD7NQLbHQ+VXxbSa/35i4tRXQAblGpCr+GrrkSohYNV+jqAuc0z8gkKGs6a6PR8gZCvDakDH6jSM9PxkOkuN6S9q09Wz7sqS7HPpgzMSEzGeFiv/Q==' >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

end
