
Vagrant.configure("2") do |config|

    config.vm.box = "debian/buster64"
  
    # The K8S master VM
    config.vm.define "k8s_master" do |k8s_master|
        k8s_master.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
      end
  
      k8s_master.vm.network "private_network", ip: "192.168.33.100"
      k8s_master.vm.hostname = "k8s-master"
  
      k8s_master.vm.provision "shell", inline: <<-SHELL
        echo "Adding SSH key"
        echo 'ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAHyKTX5ZyVK84+BdnSlfygPD6P+P8ehHPeelXxVKyeaomlKWMFB2/z1eyOtNTpFgBD7NQLbHQ+VXxbSa/35i4tRXQAblGpCr+GrrkSohYNV+jqAuc0z8gkKGs6a6PR8gZCvDakDH6jSM9PxkOkuN6S9q09Wz7sqS7HPpgzMSEzGeFiv/Q==' >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  
    # The K8S worker VM
    config.vm.define "k8s_worker_1" do |k8s_worker_1|
        k8s_worker_1.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
  
      k8s_worker_1.vm.network "private_network", ip: "192.168.33.101"
      k8s_worker_1.vm.hostname = "k8s-worker-1"
  
      k8s_worker_1.vm.provision "shell", inline: <<-SHELL
        echo "Adding SSH key"
        echo 'ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAHyKTX5ZyVK84+BdnSlfygPD6P+P8ehHPeelXxVKyeaomlKWMFB2/z1eyOtNTpFgBD7NQLbHQ+VXxbSa/35i4tRXQAblGpCr+GrrkSohYNV+jqAuc0z8gkKGs6a6PR8gZCvDakDH6jSM9PxkOkuN6S9q09Wz7sqS7HPpgzMSEzGeFiv/Q==' >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  
  end
  