
Vagrant.configure("2") do |config|

  config.vm.box = "debian/buster64"

  # The jenkins server VM
  config.vm.define "jenkins_server" do |jenkins_server|
    jenkins_server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    jenkins_server.vm.network "private_network", ip: "192.168.33.30"
    jenkins_server.vm.hostname = "jenkins-server"

    jenkins_server.vm.provision "shell", inline: <<-SHELL
      echo "Adding SSH key"
      echo 'ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAHyKTX5ZyVK84+BdnSlfygPD6P+P8ehHPeelXxVKyeaomlKWMFB2/z1eyOtNTpFgBD7NQLbHQ+VXxbSa/35i4tRXQAblGpCr+GrrkSohYNV+jqAuc0z8gkKGs6a6PR8gZCvDakDH6jSM9PxkOkuN6S9q09Wz7sqS7HPpgzMSEzGeFiv/Q==' >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

end
